name: 'Skaffold Action'
description: 'Get started with Container actions'
author: 'MightySCollins'
inputs: 
  skaffold:
    description: "Skaffold CLI: [flags] [options]"
    default: 'run'
runs:
  using: 'docker'
  image: 'Dockerfile'
